version: '3'
services:
  testsamlidp_idp:
    build: .
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: https://dashboard.batch.test/sso/saml/metadata.xml
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: https://dashboard.batch.test/sso/saml/acs
      SIMPLESAMLPHP_ADMIN_PASSWORD: admin
      SIMPLESAMLPHP_SECRET_SALT: salt
      SIMPLESAMLPHP_SP_NAME_ID_FORMAT: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress 
      SIMPLESAMLPHP_SP_NAME_ID_ATTRIBUTE: email
    ports:
    - "8088:8080"
    - "8448:8443"
    #volumes:
    #- /users.php:/var/www/simplesamlphp/config/simplesamlphp/authsources.php